In [1]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

print("\nOnes:\n", np.ones((3,4)))

print("\nZeros INT:\n", np.zeros((3,4), dtype=np.int32))
print("\nZeros:\n", np.zeros((3,4)))

print("\nRandom:\n", np.random.random((3,4)))

print("\nEmpty:\n", np.empty((4,2)))

print("\nFull N:\n", np.full((3,4),654321))

print("\nRange:\n", np.arange(0,100,5))

print("\nEvenly spaced:\n", np.linspace(0,2,20))

print("\nEye:\n", np.eye(5))

print("\nIdentity:\n", np.identity(5))


Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros INT:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Random:
 [[0.9916 0.3289 0.7996 0.4115]
 [0.7564 0.3204 0.5783 0.12  ]
 [0.8721 0.5834 0.991  0.9098]]

Empty:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Full N:
 [[654321 654321 654321 654321]
 [654321 654321 654321 654321]
 [654321 654321 654321 654321]]

Range:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

Evenly spaced:
 [0.     0.1053 0.2105 0.3158 0.4211 0.5263 0.6316 0.7368 0.8421 0.9474
 1.0526 1.1579 1.2632 1.3684 1.4737 1.5789 1.6842 1.7895 1.8947 2.    ]

Eye:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
x, y, z = np.loadtxt('teste.txt', skiprows = 1, unpack = True)

print("loadtxt ") 
print("x: ",x) 
print("y: ",y) 
print("z: ",z)

my_array2 = np.genfromtxt('teste.txt', skip_header=1, filling_values=-999)
print("my_array2: ",my_array2)

loadtxt 
x:  [1. 4.]
y:  [2. 5.]
z:  [3. 6.]
my_array2:  [[1. 2. 3.]
 [4. 5. 6.]]


In [52]:
n = np.eye(5)
m = np.full((2,2),7)
nHIGH = np.eye(50) 

np.save('teste', n)
np.savez('testH', nHIGH) 
np.savez_compressed('testH-c', nHIGH)

In [54]:
my_array = np.full((12,12), 70)
print(my_array.ndim)
print(my_array.size)
print(my_array.flags)
print(my_array.itemsize)
print(my_array.nbytes) 

2
144
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
1152


In [62]:
x = np.full((3,4), 5) 
y = np.full((2,1,4), 3)
print("x", x)
print("y", y)

res = np.add(x, y) 
print('res: ',res)

res2 = res.sum() 
print('res2: ',res2)

x [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
y [[[3 3 3 3]]

 [[3 3 3 3]]]
res:  [[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]
res2:  192


In [64]:
my_2d_array = np.random.random((4,4))
print(my_2d_array)
print(my_2d_array[1][2])
print(my_2d_array[1,2])

[[0.67847064 0.64241185 0.70701342 0.5688937 ]
 [0.79563311 0.35580207 0.07359716 0.57839184]
 [0.08497416 0.64093563 0.39830396 0.40463157]
 [0.04063125 0.36468523 0.67187747 0.49155722]]
0.07359716263171212
0.07359716263171212


### Exercícios:

* Crie um array com 10 elementos usando a função arange

* Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

* Crie duas matrizes bidimensionais com valores aleatórios

* Calcule a transposta de cada matriz

* Multiplique as duas matrizes

* Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

* Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [82]:
my_array = np.arange(1, 11)
print(my_array)
my_array = my_array.reshape((2,5))
print(my_array)

m1 = np.random.random((3,2))
m2 = np.random.random((3,2))
print(m1)
print(m2)
print(m1.transpose())
print(m2.transpose())

mult = np.dot(m1, m2.transpose())
print("Mult", mult)
add = np.concatenate((m1, m2))
print("Add", add)

np.savetxt('m1.txt', m1)
np.savetxt('m2.txt', m2)
np.savetxt('mmult.txt', mult)
np.savetxt('madd.txt', add)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.20566476 0.89171706]
 [0.6670927  0.66673919]
 [0.44215596 0.2534168 ]]
[[0.13221161 0.57120044]
 [0.58788595 0.39545009]
 [0.53023495 0.1570218 ]]
[[0.20566476 0.6670927  0.44215596]
 [0.89171706 0.66673919 0.2534168 ]]
[[0.13221161 0.58788595 0.53023495]
 [0.57120044 0.39545009 0.1570218 ]]
Mult [[0.53654045 0.47353702 0.24906966]
 [0.46903912 0.6558365  0.45840845]
 [0.20320994 0.36015098 0.27423851]]
Add [[0.20566476 0.89171706]
 [0.6670927  0.66673919]
 [0.44215596 0.2534168 ]
 [0.13221161 0.57120044]
 [0.58788595 0.39545009]
 [0.53023495 0.1570218 ]]
